name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer rnd_vF2EHJOy6dK7NWt2fI07EwTnRBfA" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/srv-d7cka0lckfvc73a4cbk0/deploys" \
            -d '{"clearCache":"do_not_clear"}'
